first homework
gatisstrauss/java-03-2023 pull request #1
Opened 2023-05-08 13:54 UTC by gatisstrauss

Completed my first homework

2023-05-09 21:03 UTC, janistumpelis requested changes
Paldies, ļoti labi, tikai pāris sīkumi jāpielabo, ieteiktu ieslēgt automātisko formatting.

2023-05-09 21:03 UTC, janistumpelis commented on Homework/src/main/java/io/codelex/arithmetic/practice/Exercise5.java
> +        boolean correct = false;
Kāda nozīme ir šim mainīgajam?

2023-05-09 21:03 UTC, janistumpelis commented on Homework/src/main/java/io/codelex/typesandvariables/practice/Exercise6.java
> +            System.out.println("The sum of the entered numbers is " + total);
Izskatās, ka šur tur nav formatting - ieteiktu ieslēgt to automātisko.

2023-05-09 21:03 UTC, janistumpelis commented on Homework/src/main/java/io/codelex/typesandvariables/practice/Exercise8.java
> +        int years = input/minutesInAYear;
Arī trūkst formatting.

2023-05-09 22:00 UTC, gatisstrauss commented
Edited my homework

2023-05-10 08:17 UTC, janistumpelis approved these changes

2023-05-10 08:19 UTC, merged